package com.specmate.cerecognition.main;

/**
 * 
 * @author Julian Frattini
 * Classes of results to evaluate the runs of the system
 */

public enum CauseEffectRecognitionResult {
	CREATION_SUCCESSFUL, CREATION_FAILED, CREATION_IMPOSSIBLE,
	RECOGNITION_SUCCESSFUL, RECOGNITION_FAILED, RECOGNITION_IMPOSSIBLE, 
	DISCARDING_SUCCESSFUL, DISCARDING_FAILED,
	DEFLECTION_SUCCESSFUL, DEFLECTION_FAILED,
	SPLITTING_SUCCESSFUL, SPLITTING_FAILED
}
